/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elevadores;

/**
 *
 * @author castr
 */
public class TelaElevador extends javax.swing.JFrame {
    ChamadaElevador chamadaElevador1;
    ChamadaElevador chamadaElevador2;
    ChamadaElevador chamadaElevador3;
    /**
     * Creates new form TelaElevador
     */
    public TelaElevador() {
        initComponents();
        chamadaElevador1 = new ChamadaElevador();
        chamadaElevador2 = new ChamadaElevador();
        chamadaElevador3 = new ChamadaElevador();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHomemUm = new javax.swing.JButton();
        btnMulherUm = new javax.swing.JButton();
        btnCriancaUm = new javax.swing.JButton();
        lblTotalUm = new javax.swing.JLabel();
        lblPesoUm = new javax.swing.JLabel();
        btnHomemDois = new javax.swing.JButton();
        btnMulherDois = new javax.swing.JButton();
        btnCriancaDois = new javax.swing.JButton();
        lblTotalDois = new javax.swing.JLabel();
        lblPesoDois = new javax.swing.JLabel();
        btnHomemTres = new javax.swing.JButton();
        btnMulherTres = new javax.swing.JButton();
        btnCriancaTres = new javax.swing.JButton();
        lblTotalTres = new javax.swing.JLabel();
        lblPesoTres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHomemUm.setText("Entrar homem");
        btnHomemUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomemUmActionPerformed(evt);
            }
        });

        btnMulherUm.setText("Entrar mulher");
        btnMulherUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulherUmActionPerformed(evt);
            }
        });

        btnCriancaUm.setText("Entrar criança");
        btnCriancaUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriancaUmActionPerformed(evt);
            }
        });

        lblTotalUm.setText("Total de passageiros no elevador: 0");

        lblPesoUm.setText("Peso total no elevador: 0kg");

        btnHomemDois.setText("Entrar homem");
        btnHomemDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomemDoisActionPerformed(evt);
            }
        });

        btnMulherDois.setText("Entrar mulher");
        btnMulherDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulherDoisActionPerformed(evt);
            }
        });

        btnCriancaDois.setText("Entrar criança");
        btnCriancaDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriancaDoisActionPerformed(evt);
            }
        });

        lblTotalDois.setText("Total de passageiros no elevador: 0");

        lblPesoDois.setText("Peso total no elevador: 0kg");

        btnHomemTres.setText("Entrar homem");
        btnHomemTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomemTresActionPerformed(evt);
            }
        });

        btnMulherTres.setText("Entrar mulher");
        btnMulherTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulherTresActionPerformed(evt);
            }
        });

        btnCriancaTres.setText("Entrar criança");
        btnCriancaTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriancaTresActionPerformed(evt);
            }
        });

        lblTotalTres.setText("Total de passageiros no elevador: 0");

        lblPesoTres.setText("Peso total no elevador: 0kg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesoTres)
                    .addComponent(lblTotalTres)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHomemTres)
                        .addGap(18, 18, 18)
                        .addComponent(btnMulherTres)
                        .addGap(18, 18, 18)
                        .addComponent(btnCriancaTres))
                    .addComponent(lblPesoDois)
                    .addComponent(lblTotalDois)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHomemDois)
                        .addGap(18, 18, 18)
                        .addComponent(btnMulherDois)
                        .addGap(18, 18, 18)
                        .addComponent(btnCriancaDois))
                    .addComponent(lblPesoUm)
                    .addComponent(lblTotalUm)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHomemUm)
                        .addGap(18, 18, 18)
                        .addComponent(btnMulherUm)
                        .addGap(18, 18, 18)
                        .addComponent(btnCriancaUm)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomemUm)
                    .addComponent(btnMulherUm)
                    .addComponent(btnCriancaUm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesoUm)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomemDois)
                    .addComponent(btnMulherDois)
                    .addComponent(btnCriancaDois))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalDois)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesoDois)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomemTres)
                    .addComponent(btnMulherTres)
                    .addComponent(btnCriancaTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesoTres)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomemUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomemUmActionPerformed
        // TODO add your handling code here:
        chamadaElevador1.entraHomem();
        lblTotalUm.setText("Total de passageiros no elevador: " + chamadaElevador1.getQtdPessoas().toString());
        lblPesoUm.setText("Peso total no elevador: " + chamadaElevador1.getPesoTotal().toString() + "kg");
        
    }//GEN-LAST:event_btnHomemUmActionPerformed

    private void btnMulherUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulherUmActionPerformed
        // TODO add your handling code here:
        chamadaElevador1.entraMulher();
        lblTotalUm.setText("Total de passageiros no elevador: " + chamadaElevador1.getQtdPessoas().toString());
        lblPesoUm.setText("Peso total no elevador: " + chamadaElevador1.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnMulherUmActionPerformed

    private void btnCriancaUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriancaUmActionPerformed
        // TODO add your handling code here:
        chamadaElevador1.entraCrianca();
        lblTotalUm.setText("Total de passageiros no elevador: " + chamadaElevador1.getQtdPessoas().toString());
        lblPesoUm.setText("Peso total no elevador: " + chamadaElevador1.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnCriancaUmActionPerformed

    private void btnHomemDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomemDoisActionPerformed
        // TODO add your handling code here:
        chamadaElevador2.entraHomem();
        lblTotalDois.setText("Total de passageiros no elevador: " + chamadaElevador2.getQtdPessoas().toString());
        lblPesoDois.setText("Peso total no elevador: " + chamadaElevador2.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnHomemDoisActionPerformed

    private void btnMulherDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulherDoisActionPerformed
        // TODO add your handling code here:
        chamadaElevador2.entraMulher();
        lblTotalDois.setText("Total de passageiros no elevador: " + chamadaElevador2.getQtdPessoas().toString());
        lblPesoDois.setText("Peso total no elevador: " + chamadaElevador2.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnMulherDoisActionPerformed

    private void btnCriancaDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriancaDoisActionPerformed
        // TODO add your handling code here:
        chamadaElevador2.entraCrianca();
        lblTotalDois.setText("Total de passageiros no elevador: " + chamadaElevador2.getQtdPessoas().toString());
        lblPesoDois.setText("Peso total no elevador: " + chamadaElevador2.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnCriancaDoisActionPerformed

    private void btnHomemTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomemTresActionPerformed
        // TODO add your handling code here:
        chamadaElevador3.entraHomem();
        lblTotalTres.setText("Total de passageiros no elevador: " + chamadaElevador3.getQtdPessoas().toString());
        lblPesoTres.setText("Peso total no elevador: " + chamadaElevador3.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnHomemTresActionPerformed

    private void btnMulherTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulherTresActionPerformed
        // TODO add your handling code here:
        chamadaElevador3.entraMulher();
        lblTotalTres.setText("Total de passageiros no elevador: " + chamadaElevador3.getQtdPessoas().toString());
        lblPesoTres.setText("Peso total no elevador: " + chamadaElevador3.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnMulherTresActionPerformed

    private void btnCriancaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriancaTresActionPerformed
        // TODO add your handling code here:
        chamadaElevador3.entraCrianca();
        lblTotalTres.setText("Total de passageiros no elevador: " + chamadaElevador3.getQtdPessoas().toString());
        lblPesoTres.setText("Peso total no elevador: " + chamadaElevador3.getPesoTotal().toString() + "kg");
    }//GEN-LAST:event_btnCriancaTresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaElevador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriancaDois;
    private javax.swing.JButton btnCriancaTres;
    private javax.swing.JButton btnCriancaUm;
    private javax.swing.JButton btnHomemDois;
    private javax.swing.JButton btnHomemTres;
    private javax.swing.JButton btnHomemUm;
    private javax.swing.JButton btnMulherDois;
    private javax.swing.JButton btnMulherTres;
    private javax.swing.JButton btnMulherUm;
    private javax.swing.JLabel lblPesoDois;
    private javax.swing.JLabel lblPesoTres;
    private javax.swing.JLabel lblPesoUm;
    private javax.swing.JLabel lblTotalDois;
    private javax.swing.JLabel lblTotalTres;
    private javax.swing.JLabel lblTotalUm;
    // End of variables declaration//GEN-END:variables
}
